Story/iexp 166
upconsulting/IsisCB pull request #741
Opened 2022-02-21 19:57 UTC by crispzips

2022-02-26 01:56 UTC, jdamerow requested changes
- When there are no featured citations (which is the case when the code is first deployed), the homepage throws
```
ValueError at /
empty range for randrange() (0, 0, 0)
```

- I've added featured authorities with and enddate 2022-02-24 and then changed the enddate to 25 and then 26. The page still tells me that there are only past featured authorities and no current ones. 
- also the past featured table doesn't contain anything (although it says there are 166 past featured authorities)
- and when I entered a featured citation with dates 2022-02-26 to 2022-02-27, it shows up as currently featured

2022-02-26 01:56 UTC, jdamerow commented on isiscb/curation/views.py
> +    now = datetime.datetime.now(pytz.timezone('US/Central'))
As a general rule: hard-coded strings are bad, especially when they are project specific configurations/strings.

2022-02-26 01:56 UTC, jdamerow commented on isiscb/isisdata/views.py
> +            return {}
same as above

2022-02-26 01:56 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        print(recent_tweet)
remove

2022-02-26 01:56 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    properties = featured_citation.acrelation_set.exclude(type_controlled__in=['AU', 'ED', 'CO', 'SU', 'CA']).filter(public=True)
use constants

2022-02-26 01:56 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    ###
I would put all the above twitter related code into a new file that holds twitter related functions. In fact, it might make sense to create a twitter class with two methods for the above code.

2022-02-26 01:56 UTC, jdamerow commented on isiscb/curation/views.py
> +                FeaturedAuthority.objects.filter(authority_id__in=authority_ids).delete()
what does the else block do? it needs at least a comment.

2022-02-26 01:56 UTC, jdamerow commented on isiscb/curation/views.py
> +    past_featured = FeaturedAuthority.objects.filter(end_date__lt=now)
this will eventually be many, many objects that you don't want to all retrieve from the database; maybe the else block below is supposed to delete old objects but if so I don't quite understand under what conditions.

2022-02-27 01:07 UTC, crispzips commented
> 

I resolved the problem with the random selection but I'm not having any of the problems setting/updating the dates of the featured authorities that you mentioned above, except, with this issue: "and when I entered a featured citation with dates 2022-02-26 to 2022-02-27, it shows up as currently featured" -- that's happening because whether a featured authority is current is based on the current day in Central US time, but the start and end dates are saved in GMT time

2022-02-28 01:03 UTC, jdamerow commented
Resolve conflicts please

2022-02-28 01:32 UTC, jdamerow requested changes
The homepage works now. There are some elements though that seem to not belong there (maybe it's actually the legend for the diagram?): at the bottom left
![image](https://user-images.githubusercontent.com/8881141/155910168-b52059b1-f704-4730-b8e9-c57a79843d0f.png)

2022-02-28 01:32 UTC, jdamerow commented on isiscb/curation/views.py
> +            print(request.POST)
remove print statements

2022-02-28 01:32 UTC, jdamerow commented on isiscb/curation/templates/curation/base.html
> +        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymo
there are still two versions of font awesome

2022-02-28 01:32 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        featured_citation = get_object_or_404(Citation, pk=featured_citation.id)
I'm fairly certain this will cause a 404 error if the citation doesn't exist. Since it is the homepage/landing page that would break the entry point for many people should the featured citation not exist for some reason.

2022-02-28 01:32 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        featured_citation = get_object_or_404(Citation, pk=settings.FEATURED_CITATION_ID)
see above

2022-02-28 01:32 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    featured_citation_authors = featured_citation.acrelation_set.filter(type_controlled__in=['AU', 'CO', 'ED'], citation__public=True, public=True)
use constants

2022-02-28 01:32 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        featured_authority = get_object_or_404(Authority, pk=settings.FEATURED_AUTHORITY_ID)
see above

2022-02-28 01:32 UTC, jdamerow commented on isiscb/isisdata/views.py
> +            return {}
still the same question

2022-02-28 01:32 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    ###
in a new file (the view files are getting huge and I'm trying to cut them down piece by piece)

2022-03-28 01:45 UTC, jdamerow requested changes

2022-03-28 01:45 UTC, jdamerow commented on isiscb/curation/templates/curation/authorities_featured.html
> +            {% if field.label != 'Fields' %}
Is this if necessary here? This looks like it was copied from another form where this was needed, but is it needed here?

2022-03-28 01:45 UTC, jdamerow commented on isiscb/curation/views.py
> +            print(request.POST)
those still need to be removed

2022-03-28 01:45 UTC, jdamerow commented on isiscb/curation/views.py
> +    if request.GET.get('confirmed', False):
what's the point of this if statement if confirmed will always be true? Why not just check if it's a post request?

2022-03-28 01:45 UTC, jdamerow commented on isiscb/isisdata/templatetags/app_filters.py
> +        return "Count"
```suggestion
         if not sort_field or 'count' in sort_field:
             return 'Count'
```

2022-03-28 01:45 UTC, jdamerow commented on isiscb/isisdata/templatetags/app_filters.py
> +        return "Count"
and then remove the if below

2022-03-28 01:45 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        featured_citation = get_object_or_404(Citation, pk=featured_citation.id)
This is still an issue

2022-03-28 01:45 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        featured_citation = get_object_or_404(Citation, pk=settings.FEATURED_CITATION_ID)
see above

2022-03-28 01:45 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    featured_citation_authors = featured_citation.acrelation_set.filter(type_controlled__in=['AU', 'CO', 'ED'], citation__public=True, public=True)
this

2022-03-28 01:45 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        featured_authority = get_object_or_404(Authority, pk=settings.FEATURED_AUTHORITY_ID)
this

2022-03-28 01:45 UTC, jdamerow commented on isiscb/isisdata/views.py
> +            return {}
this

2022-03-28 01:45 UTC, jdamerow commented on isiscb/isisdata/views.py
> +            return {}
this

2022-03-29 01:24 UTC, jdamerow requested changes
I get an exception:
```
Traceback (most recent call last):
  File "/Users/jdamerow/UpConsulting/venv3-es/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/jdamerow/UpConsulting/venv3-es/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jdamerow/UpConsulting/isiscb/IsisCB/isiscb/isisdata/views.py", line 1472, in home
    featured_citation_authors = featured_citation.acrelation_set.filter(type_controlled__in=[ACRelation.AUTHOR, ACRelation.CONTRIBUTOR, ACRelation.EDITOR], citation__public=True, public=True)
AttributeError: 'QuerySet' object has no attribute 'acrelation_set'
```

Also, there are unaddressed comments.

2022-03-29 01:24 UTC, jdamerow commented on isiscb/curation/views.py
> +    if request.GET.get('confirmed', False):
this still

2022-03-29 01:24 UTC, jdamerow commented on isiscb/isisdata/views.py
>      if not (citation.BOOK or citation.CHAPTER):
Those should use the constant from the class: `Citation.BOOK`

2022-03-29 01:24 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        featured_citation = featured_citations[random.randint(0,len(featured_citations)-1)]
it seems like this line returns a queryset not a citation, so I get all kind of follow up errors (like the one I mention in the overall comment) and like this one:
```
Traceback (most recent call last):
  File "/Users/jdamerow/UpConsulting/venv3-es/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/jdamerow/UpConsulting/venv3-es/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jdamerow/UpConsulting/isiscb/IsisCB/isiscb/isisdata/views.py", line 1472, in home
    featured_citation_image = get_google_books_image(featured_citation, True)
  File "/Users/jdamerow/UpConsulting/isiscb/IsisCB/isiscb/isisdata/views.py", line 939, in get_google_books_image
    if not (citation.BOOK or citation.CHAPTER):
AttributeError: 'QuerySet' object has no attribute 'BOOK'
```

2022-03-29 14:15 UTC, crispzips commented on isiscb/isisdata/views.py
> +        featured_citation = featured_citations[random.randint(0,len(featured_citations)-1)]
it was when i changed the method for getting the featured citation from get_object_or_404 to Citation.objects.filter I forgot that filter always returns a list even when you request a specific item based on pk

2022-03-31 01:38 UTC, jdamerow requested changes

2022-03-31 01:38 UTC, jdamerow commented on isiscb/isisdata/twitter_methods.py
> +            recent_tweet_url = recent_tweet_text[recent_tweet_text.rfind('https://'):]
if response is not successful, the above variables will be set to '' in the above `if` statement but then you still try to set them here. I would think that at least one of these lines will raise an exception (e.g. trying to get data->text from an unsuccessful response).

2022-03-31 01:38 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        featured_citation = Citation.objects.filter(pk=featured_citation.id)[0]
I would use `first()` here instead of `[0]`. Should for some reason the index have stale data in it and the citation with the id doesn't exist anymore for some reason, this will raise an exception. `first` will simply return None.

2022-03-31 14:13 UTC, crispzips commented on isiscb/isisdata/twitter_methods.py
> +            recent_tweet_url = recent_tweet_text[recent_tweet_text.rfind('https://'):]
can i just put everything else in an else block of the if !200?

2022-03-31 14:13 UTC, crispzips commented on isiscb/isisdata/views.py
> +        featured_citation = Citation.objects.filter(pk=featured_citation.id)[0]
ok that's good to know in general i just assumed they were synonyms -- thanks for the tip

2022-04-02 00:46 UTC, jdamerow requested changes
There is still an unaddressed comment.

2022-04-02 00:46 UTC, jdamerow commented on isiscb/curation/templates/curation/authorities_featured.html
> +            {% if field.label != 'Fields' %}
This still

2022-04-02 00:46 UTC, jdamerow commented on isiscb/isisdata/twitter_methods.py
> +        else:
Doesn't change the logic, but you don't need the `else` here since the if returns.

2022-04-02 00:46 UTC, jdamerow commented on isiscb/isisdata/twitter_methods.py
> +    recent_tweet_id = recent_tweets['data'][random.randint(0,len(recent_tweets['data'])-1)]['id'] if 'data' in recent_tweets else ''
I think you also want to make sure that `len(recent_tweets['data']) > 0`? otherwise I think this line will throw an error.

2022-04-02 00:46 UTC, jdamerow commented on isiscb/isisdata/twitter_methods.py
> +                URL_REGEX = re.compile(r'''((?:https://).{15})''')
capitalizing the whole variable name is odd; this is usually reserved for constants, which this variable isn't really since it's defined halfway through the method.

2022-04-02 00:49 UTC, jdamerow commented
Now I get this:
`'QuerySet' object has no attribute 'id'`
for
```
/Users/jdamerow/UpConsulting/isiscb/IsisCB/isiscb/isisdata/views.py, line 1480, in home
    featured_authority_wikipedia_data = WikipediaData.objects.filter(authority__id=featured_authority.id).first() 
```
Does the code run for you?

2022-04-02 12:47 UTC, crispzips commented
> 

it runs for me. the reason it doesn't run for you is that you haven't visited that authority page before and therefore the wikipedia data for that page hasn't been inserted into the WikipediaData table. The way the code is set up right now requires that all of the featured authorities' pages have been visited.

2022-04-02 12:49 UTC, crispzips commented
> > 
> 
> it runs for me. the reason it doesn't run for you is that you haven't visited that authority page before and therefore the wikipedia data for that page hasn't been inserted into the WikipediaData table. The way the code is set up right now requires that all of the featured authorities' pages have been visited.

the reason i did that was to avoid having to do everything necessary to go get the wikipedia data

2022-04-03 00:13 UTC, jdamerow commented
That sounds like a guaranteed exception at some point. Since there are thousands of authorities, it's not unthinkable that an authority (on purpose or not) is selected to be features. Right now that would break the main page, which would be pretty bad. The code to load wikipediadata should be encapsulated so that you can call it from whereever you need it (authority page or main page).

2022-04-03 04:30 UTC, crispzips commented
> That sounds like a guaranteed exception at some point. Since there are thousands of authorities, it's not unthinkable that an authority (on purpose or not) is selected to be features. Right now that would break the main page, which would be pretty bad. The code to load wikipediadata should be encapsulated so that you can call it from whereever you need it (authority page or main page).

i will fix it. the wikipedia code is encapsulated but it takes inputs from the authority view that aren't currently present in, but need to be added to, the home view

2022-04-03 13:29 UTC, StephenPWeldon commented
Thanks, Paul, I was going to suggest the same. We don’t want to create case
in which a Wikipedia call could shut down a page on the system. In general,
we want to be entirely self sufficient in the event anything we don’t have
control over changes. I don’t mind a blank space or even a small note on
the page where something is missing, but it should not break the page.

On Sat, Apr 2, 2022 at 11:30 PM Paul Kelley Vieth ***@***.***>
wrote:

> That sounds like a guaranteed exception at some point. Since there are
> thousands of authorities, it's not unthinkable that an authority (on
> purpose or not) is selected to be features. Right now that would break the
> main page, which would be pretty bad. The code to load wikipediadata should
> be encapsulated so that you can call it from whereever you need it
> (authority page or main page).
>
> i will fix it. the wikipedia code is encapsulated but it takes inputs from
> the authority view that aren't currently present in, but need to be added
> to, the home view
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/upconsulting/IsisCB/pull/741#issuecomment-1086774481>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADE5NZG3LBN6T3CFP22XPETVDENFXANCNFSM5O7PGZCQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-04-06 01:07 UTC, jdamerow requested changes
There is still an exception on the home page (see comment in code).

And a couple of things I've noticed on the curation site:
- I've added authorities to be featured start date 2022-04-04, end date 2022-04-06: they do not show up under currently featured
- you probably want to add a note about what formats dates in start and end date should be in (e.g. YYYY-MM-DD)
- the past featured authorities don't seem to be ordered in any way, e.g. most recent enddate first

2022-04-06 01:07 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    related_citations_count = sqs.all().exclude(public="false").filter_or(author_ids=featured_authority.id).filter_or(contributor_ids=featured_authority.id) \
this line still throws an error `'QuerySet' object has no attribute 'id'` in line 1484. Probably because of line 1479.

2022-04-06 01:07 UTC, jdamerow commented on isiscb/isisdata/templates/isisdata/authority_fragments/fragment_authority_places_facet.html
> +            console.log(jsonData.countries);
remove console log output

2022-04-06 13:11 UTC, crispzips commented on isiscb/isisdata/templates/isisdata/authority_fragments/fragment_authority_places_facet.html
> +            console.log(jsonData.countries);
oops. i was changing the color scale from continuous to discrete

2022-04-06 13:13 UTC, crispzips commented
> There is still an exception on the home page (see comment in code).
> 
> And a couple of things I've noticed on the curation site:
> 
> * I've added authorities to be featured start date 2022-04-04, end date 2022-04-06: they do not show up under currently featured
> * you probably want to add a note about what formats dates in start and end date should be in (e.g. YYYY-MM-DD)
> * the past featured authorities don't seem to be ordered in any way, e.g. most recent enddate first

depending on the time of day, if you set the enddate for tomorrow, it will get filed under past featured because of timezone mismatching

2022-04-07 00:42 UTC, jdamerow commented
That's very unintuitive. If the comparison is done with a date in the admin timezone, the start/end dates should also be stored in the admin time zone, so that if end date is April 7, that means until the end of the previous day in the admin timezone. Otherwise what's the point of using a specific timezone at all?

2022-04-07 00:45 UTC, jdamerow requested changes

2022-04-07 00:45 UTC, jdamerow commented on isiscb/isisdata/templatetags/app_filters.py
> +        return settings.URI_PREFIX + "authority/" + id
indentation is too much

2022-04-11 01:02 UTC, jdamerow commented on isiscb/curation/templates/curation/authorities_featured.html
> +                            <td>{{authority.end_date|adjust_datetime_hours:"-5"|date:"Y-m-d G:i"}}</td>
I have a few issues with this solution: 
- -5 is hardcoded, meaning if the timezone changes for some reason, we'll have to hunt down all the instances where this filter is used to fix it (it's just this one file at the moment but who knows where else this will be used in the future). If we even remember that this filter needs fixing.
- what if for some reason the time is not passed in as UTC anymore at some point (either server location changes, db, changes, django updates, etc)? Then this will result in the wrong timezone.
- There seems to be a django tag for displaying timezoned dates (I didn't know it existed until I googled it just now): https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/#timezone
  Just put the admin timezone setting into the context and use it in the tag. That should work I believe.

2022-04-12 01:05 UTC, merged