Story/iexp 331
upconsulting/IsisCB pull request #746
Opened 2022-05-05 22:41 UTC by crispzips

2022-05-06 01:02 UTC, jdamerow commented
Resolve conflicts please

2022-05-06 01:04 UTC, crispzips commented
> Resolve conflicts please

ah -- it's the settings that are personal to my local environment... one sec

2022-05-06 01:39 UTC, jdamerow requested changes
- we might have some issues with these migrations. In the PR that is merged by now, you've added one migration file `0096_featuredauthority_googlebooksdata_wikipediadata.py`. That one does not appear here but there are two other 0096 migration files here plus a merging migration. I suspect this will create issues. Please merge develop into this branch and then see if the migrations still run without errors.

I didn't get much further than that because of missing settings (e.g. `'Settings' object has no attribute 'ADMIN_TIMEZONE'`). Also, I got this error on one page:
`AttributeError at /isis/citation/CBB001451692/`
`'NoneType' object has no attribute 'type_controlled'`
in this line
`similar_objects[acrelation.authority.type_controlled].append(acrelation.authority) `

2022-05-06 01:39 UTC, jdamerow commented on isiscb/isisdata/isiscbviews/authority_views.py
> +
it looks like this method is pretty much a copy of the previous one (at least in parts). This should be much more DRY (don't repeat yourself). Extract common code into methods and call those instead.

2022-05-06 01:39 UTC, jdamerow commented on isiscb/isisdata/templatetags/app_filters.py
> +        return link + "?" + key + "=" + str(page_number)
how do you know that the link does not already contain `?`? What if the link is something like `.../authority/XXX?param=value`?

2022-05-06 01:39 UTC, jdamerow commented on isiscb/isisdata/templatetags/citation_filters.py
> +    return citation
merge with line 11

2022-05-06 03:07 UTC, crispzips commented on isiscb/isisdata/templatetags/app_filters.py
> +        return link + "?" + key + "=" + str(page_number)
I'm confused about what you're asking. If the link is something like `.../authority/XXX?param=value` as you say then it replaces `param=value` with the desired param and value. If you trying to put an extra `?` in a url then the url pattern manager just ignores that

2022-05-06 03:09 UTC, crispzips commented
> * we might have some issues with these migrations. In the PR that is merged by now, you've added one migration file `0096_featuredauthority_googlebooksdata_wikipediadata.py`. That one does not appear here but there are two other 0096 migration files here plus a merging migration. I suspect this will create issues. Please merge develop into this branch and then see if the migrations still run without errors.
> 
> I didn't get much further than that because of missing settings (e.g. `'Settings' object has no attribute 'ADMIN_TIMEZONE'`). Also, I got this error on one page: `AttributeError at /isis/citation/CBB001451692/` `'NoneType' object has no attribute 'type_controlled'` in this line `similar_objects[acrelation.authority.type_controlled].append(acrelation.authority) `

for some reason i messed up the settings file when i was merging develop into 331 (I thought I told it to keep the all of the settings but i must have clicked accept incoming changes from develop)

2022-05-06 03:15 UTC, crispzips commented
> * we might have some issues with these migrations. In the PR that is merged by now, you've added one migration file `0096_featuredauthority_googlebooksdata_wikipediadata.py`. That one does not appear here but there are two other 0096 migration files here plus a merging migration. I suspect this will create issues. Please merge develop into this branch and then see if the migrations still run without errors.
> 
> I didn't get much further than that because of missing settings (e.g. `'Settings' object has no attribute 'ADMIN_TIMEZONE'`). Also, I got this error on one page: `AttributeError at /isis/citation/CBB001451692/` `'NoneType' object has no attribute 'type_controlled'` in this line `similar_objects[acrelation.authority.type_controlled].append(acrelation.authority) `

when i ran the migration i got this error:
```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0096_featuredauthority_googlebooksdata_wikipediadata, 0099_featuredauthority in isisdata).
To fix them run 'python manage.py makemigrations --merge'
```

so i ran `python manage.py makemigrations --merge` and it said this:

```
Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N] 
```
so i typed `y` and it did it's thing and then i ran `python manage.py migrate` again got this error: `django.db.utils.ProgrammingError: relation "isisdata_featuredauthority" already exists`

2022-05-09 01:23 UTC, jdamerow requested changes
I'm not done yet. Will continue tomorrow. Here are my comments for now.

2022-05-09 01:23 UTC, jdamerow commented on isiscb/isisdata/templatetags/app_filters.py
> +        return link + "?" + key + "=" + str(page_number)
What I'm saying is that if the url is something like this (I know it's the wrong view but to demonstrate):
`http://isiscb-staging-p3-2.us-west-2.elasticbeanstalk.com/isis/?q=einstein&sort_order_citation=publication_date_for_sort&sort_order_dir_citation=descend` 
and we want to append `models=isisdata.authority`, then your code would create:
`http://isiscb-staging-p3-2.us-west-2.elasticbeanstalk.com/isis/?q=einstein&sort_order_citation=publication_date_for_sort&sort_order_dir_citation=descend?models=isisdata.authority` right?
However, this url doesn't work. The last parameter/value pair is not recognized. If you paste this url into your browser it goes to the citation results, not authority results. For this to work you need to change it to:
`http://isiscb-staging-p3-2.us-west-2.elasticbeanstalk.com/isis/?q=einstein&sort_order_citation=publication_date_for_sort&sort_order_dir_citation=descend&models=isisdata.authority`
Does that make sense?

2022-05-09 01:23 UTC, jdamerow commented on isiscb/isisdata/templatetags/search_filters.py
> +        'Bibliographic List': ' label-default',
you should use the type codes not the display text here (e.g.  PE instead of 'Person'). The codes shouldn't ever change, the label might (which would break this code).

2022-05-09 01:23 UTC, jdamerow commented on isiscb/isisdata/templatetags/search_filters.py
> +        return mark_safe('<span class="h4" style="margin: 0">' + name + '&nbsp<span class="label' + authority_type_label_map[authority_type] + '">' + authority_type + '</span></span>')
What if we add another type that's not in the list? There needs to be a fallback option.

2022-05-19 01:29 UTC, jdamerow requested changes

2022-05-19 01:29 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        cover_image['url'] = google_books_data.image_url
if you return `cover_image` after this line, you don't need this huge else block (you can remove `else` and decrease the indentation for the rest of the code). It would be a lot easier to read.

2022-05-19 01:29 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        if title:
so if there is no title then there is no call to google, right? if you add an if statement after line 977, and return there if there is no title, you don't need this if. Makes it easier to read and understand what happens.

2022-05-19 01:29 UTC, jdamerow commented on isiscb/isisdata/views.py
> +            if bookGoogleId:
same as before, if you turn this if around, you can just say "if there is no id, then return empty dict". easier to read and undestand.

2022-05-19 01:29 UTC, jdamerow commented on isiscb/isisdata/views.py
> +def rank(facets):
this method needs a comment what it does

2022-05-19 01:29 UTC, jdamerow commented on isiscb/isisdata/views.py
> +        authority = Authority.objects.get(id=authority_id)
have you tried just making one db call with `id_in=authority_ids` (not sure if that actually works but I would think so) and then use list comprehension to get all names?

2022-05-25 02:15 UTC, jdamerow requested changes

2022-05-25 02:15 UTC, jdamerow commented on isiscb/isisdata/templatetags/app_filters.py
> +        return re.sub(key + "=[0-9]+", key + "=" + str(page_number), link)
what is `key` and `sort_str`? This method seems to make the assumption that whatever parameter is passed in has only numbers as values. If that's the case there needs to be some comments explaining what the assumptions are. And what is `sort_str`? It doesn't seem to have sorting information but page information?

2022-05-25 02:15 UTC, jdamerow commented on isiscb/isisdata/templatetags/app_filters.py
> +            new_link = new_link + "&"
the above lines can be condensed to 
`new_link = new_link + "?" if "?" not in new_link else new_link + "&"`

2022-05-25 02:15 UTC, jdamerow commented on isiscb/isisdata/templatetags/search_filters.py
> +        'BL': ' label-default',
these should all use the constant defined in the model

2022-05-25 02:15 UTC, jdamerow commented on isiscb/isisdata/templatetags/search_filters.py
> +            authority_type = "CO"
same here

2022-05-25 02:15 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    # This method arranges facet box items by related citation count in descending order
I'm confused. Is this just sorting the list of facets? If so, can't you use `sort`?

2022-05-25 02:15 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    # This method arranges facet box items by related citation count in descending order
I'm getting more and more confused about what this function does. An example would probably be good.

2022-05-25 03:02 UTC, crispzips commented on isiscb/isisdata/views.py
> +    # This method arranges facet box items by related citation count in descending order
facets is a list of tuples, e.g. [(CBA123456789, 37), . . .] with each tuple containing an authority and the facet count. so that's why i did it that way. Can you sort lists of tuples the ways a list of dict is sorted here: https://www.w3schools.com/python/ref_list_sort.asp by creating a function that serves as the key for the sorting?

2022-05-25 15:56 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    # This method arranges facet box items by related citation count in descending order
I can't see why not. The parameter for the function would just get a tuple instead of an int or string or something.

2022-06-05 21:58 UTC, jdamerow requested changes

2022-06-05 21:58 UTC, jdamerow commented on isiscb/isisdata/isiscbviews/authority_views.py
> +    _handle_authority_redirects(authority)
this method returns something in certain cases but this isn't reflected here.

2022-06-05 21:58 UTC, jdamerow commented on isiscb/isisdata/isiscbviews/authority_views.py
> +    _handle_authority_redirects(authority)
see previous comment about return value of this function

2022-06-05 21:58 UTC, jdamerow commented on isiscb/isisdata/views.py
> +    # This method arranges facet box items by related citation count in descending order and assigns a rank to each facet. Facets with the same count are assinged the same rank even though they'll ha
let's break this up over several lines so it doesn't require endless scrolling to read.

2022-06-07 18:32 UTC, crispzips commented on isiscb/isisdata/isiscbviews/authority_views.py
> +    _handle_authority_redirects(authority)
i thought it just returned HttpResponses?

2022-06-08 01:41 UTC, jdamerow commented on isiscb/isisdata/isiscbviews/authority_views.py
> +    _handle_authority_redirects(authority)
the method returns a response object but you're not assigning the returned object to a variable and do something with it. So even if this method returns a `HttpResponseForbidden` or something, this method is not returning in this line. does that make sense?

2022-06-08 01:46 UTC, crispzips commented on isiscb/isisdata/isiscbviews/authority_views.py
> +    _handle_authority_redirects(authority)
so these two methods just need to be assigned to variables?

2022-06-09 01:45 UTC, merged