Story/iexp 346
upconsulting/IsisCB pull request #764
Opened 2022-09-02 01:15 UTC by crispzips

2022-09-07 01:39 UTC, jdamerow requested changes
I think there are a lot of changes in this branch that don't belong to this ticket but the citation creation ticket?

2022-09-07 01:39 UTC, jdamerow commented on isiscb/curation/forms.py
> +        #  self.fields['administrator_notes'].widget.attrs['placeholder'] = 'test'
is this needed?

2022-09-07 01:39 UTC, jdamerow commented on isiscb/curation/forms.py
> +            # self.fields['type_controlled'].widget = forms.widgets.HiddenInput()
is there a reason this is commented out?

2022-09-07 01:39 UTC, jdamerow commented on isiscb/curation/rules.py
> +    return True
this looks like from the other ticket?

2022-09-07 01:39 UTC, jdamerow commented on isiscb/curation/rules.py
> +
this too?

2022-09-07 01:39 UTC, closed without merging

2022-10-26 13:43 UTC, crispzips commented on isiscb/curation/rules.py
> +
I got rid of all this stuff from the other ticket.. I think it got left in there because I branched from that ticket in order to keep some of its changes to the user interface