[IEXP-372] autogenerate categories
upconsulting/IsisCB pull request #777
Opened 2022-12-20 17:55 UTC by crispzips

ok I remade this on a new branch branched from develop instead of from another branch I was still working on which is what I had accidentally done originally

2023-01-01 20:13 UTC, jdamerow requested changes

2023-01-01 20:13 UTC, jdamerow commented on isiscb/curation/views.py
> +def generate_category(request):
also, does this method generate one category or many (many, right)? If many, it should be called `...categories` (plural). Also, it doesn't generate the categories, does it? Just some suggestions (so maybe call it `generate_category_suggestions` or something like that)?

2023-01-01 20:13 UTC, jdamerow commented on isiscb/curation/views.py
> +        citation_id = request.POST.get('citation_id')
And then you can do a `get_object_or_404` with the citation id at the beginning of the method to make sure a 404 is thrown should someone call the url with a citation id that doesn't exist anymore.

2023-01-01 20:13 UTC, closed without merging

2023-01-02 17:14 UTC, crispzips commented on isiscb/curation/views.py
> +def generate_category(request):
good point. I wasn't sure if there was a system of organization in the view file

2023-01-02 21:38 UTC, crispzips commented on isiscb/curation/views.py
> +            similar_citations_category_ids = [(acrelation.authority.name, acrelation.authority.id) for acrelation in similar_citations_category_acrelations if acrelation.authority]
ok I skipped this reiteration by using values_list, but I couldn't figure out how to do it with the line you recommended above because I can't figure out how to use values_list and get_results() together

2023-01-03 01:51 UTC, jdamerow commented on isiscb/curation/views.py
> +            'category_guesses': categories,
also, if subjects is None or empty, this line throws `UnboundLocalError: local variable 'categories' referenced before assignment`

2023-01-03 01:52 UTC, jdamerow commented on isiscb/curation/views.py
> +    if request.method == 'POST':
and also, this does not need to be a POST request, does it? It's just querying data not changing anything, so that's typically GET requests.