[IEXP-488] html snippetting functionality for newsletter
upconsulting/IsisCB pull request #805
Opened 2024-01-24 22:06 UTC by crispzips

2024-01-25 02:58 UTC, jdamerow requested changes
- there is a migration that fails (I don't think you need the migration?)

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +    if len(contribs):
`if contribs` should do the same thing, shouldn't it? You're just testing for an empty list?

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +        for index, contrib in enumerate(contribs):
there needs to be some heavy commenting for this for loop with examples which case each if statement handles.

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +
if index is >2, we can break the loop, can't we?

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +    # format contributors
this should probably all go in its own function and there should be test cases for that function.

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +        formatted_title = formatted_title + '"' + title + '."'
same here: own function and test cases into the function. also I suggest creating a utility class whose objects you initialize with the citation in question and then in the tag you simply call `get_formatted_citation`. This is too much code for a tag.

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +    # format date
own method in class

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +        isbn = [linked_datum if linked_datum.type_controlled == 'ISBN' else None for linked_datum in citation.linkeddata_public][0]
I think we have a constant for `type_controlled`?

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/views.py
>          'objects': filtered_objects,
is there a reason you don't just use `filtered_objects.qs` in the template?

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/views.py
> +    if isinstance(queryset, CitationFilter) or isinstance(queryset, AuthorityFilter):
can this ever be an authority filter?

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/views.py
> +    context = {}
define in line 2334

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/views.py
> +    context.update({
add to  context definition before; no need for two update calls, should just be:
```
context = {
'citations': ...,
...
'object_type':...
}
```

2024-01-25 02:58 UTC, jdamerow commented on isiscb/isisdata/isiscbviews/citation_views.py
> +    print(objects)
remove

2024-01-25 02:58 UTC, jdamerow commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                    </div>
the content of these if-boxes is the same for all facets, right? Just a different title? It would make it a lot more readable if you create a fragment for the boxes and use the [`include` functionality.](https://docs.djangoproject.com/en/5.0/ref/templates/builtins/#include)

2024-01-25 22:09 UTC, crispzips commented on isiscb/curation/templatetags/general_tags.py
> +        formatted_title = formatted_title + '"' + title + '."'
should it go in the isisdata/utils.py or should I create a file for holding utility class in the curation part of the file tree?

2024-01-25 22:22 UTC, crispzips commented on isiscb/curation/templatetags/general_tags.py
> +        isbn = [linked_datum if linked_datum.type_controlled == 'ISBN' else None for linked_datum in citation.linkeddata_public][0]
I have tried `if linked_datum.type_controlled == LInkedData.ISBN` and `if linked_datum.type_controlled == LInkedDataType.ISBN` and gotten the error that `type object 'LinkedData' has no attribute 'ISBN'` and `type object 'LinkedDataType' has no attribute 'ISBN'`

2024-01-25 22:36 UTC, crispzips commented on isiscb/curation/templatetags/general_tags.py
> +        isbn = [linked_datum if linked_datum.type_controlled == 'ISBN' else None for linked_datum in citation.linkeddata_public][0]
the type options for linked data aren't specified in the model, they're user-defined in a separate table called LinkedDataType -- maybe that has something to do with it?

2024-01-25 23:08 UTC, crispzips commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                    </div>
I don't know why I didn't just assume so, but I didn't know you could pass data to included templates (or that they inherited context from the template they're included in) so this was a valuable lesson for me

2024-01-26 02:42 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +    # format contributors
it's a perfect case for unit tests. Similar to the ones found in the other apps (e.g. https://github.com/upconsulting/IsisCB/blob/master/isiscb/zotero/tests.py and https://github.com/upconsulting/IsisCB/blob/master/isiscb/isisdata/tests/test_acrelation_types.py). You can create a new file in curation (maybe let's call it `tests.py` for now), paste the following stub:
```
import unittest

class TestSnippets(unittest.TestCase):
    def test_<function_to_test>(self):
        ...


if __name__ == '__main__':
    unittest.main()
```
and then when you run `python manange.py test curation`, it will execute them. If you want to meet to talk about unit testing, let me know.

This might also help: https://realpython.com/python-testing/

2024-01-26 02:43 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +        formatted_title = formatted_title + '"' + title + '."'
it should be with the curation part

2024-01-26 02:46 UTC, jdamerow commented on isiscb/curation/templatetags/general_tags.py
> +        isbn = [linked_datum if linked_datum.type_controlled == 'ISBN' else None for linked_datum in citation.linkeddata_public][0]
ah ja, one of these beautifully designed issues of the system... just forget about my comments, there is really no better way right now. The only thing I could think of right now would be to make it a configurable value loaded in the settings.

2024-01-26 02:49 UTC, jdamerow commented
If it ran already locally, you probably have to [undo the migration first](https://stackoverflow.com/questions/32123477/how-to-revert-the-last-migration), and the `git rm file.name` should remove the file from Git.

2024-01-28 17:28 UTC, crispzips commented
Can we deploy this to the staging survey with the changes that I've already made and then I can create the tests after the fact because I know Dr. Weldon is anxious to get this newsletter functionality out so Judy Kaplan can start publishing newsletters?

I want to learn testing and I know its an essential skill.

2024-01-28 21:19 UTC, jdamerow requested changes
- when there is an incomplete ACRelation, a `'NoneType' object has no attribute 'name'` is thrown in
```
/Users/jdamerow/UpConsulting/isiscb/IsisCB/isiscb/curation/utils.py, line 36, in <listcomp>
    contribs = [contrib_acrelation.authority.name for contrib_acrelation in contrib_acrelations] 
```
- For some reason the logout button on curation is now gone but the file does not show up as changed.
- for the facet boxes, I believe the links will always be relative, so if the html is intended to be copied into a newsletter, the links won't work.
- on the authority page, in the generate html model, when I click "Generate HTML" multiple times, it appends the same html again so that there are multiple html blocks of the same code copied.
- and also, there seems to be a bunch of javascript being generated that doesn't seem relevant
- and the model does not have a close button

2024-01-28 21:19 UTC, jdamerow commented on isiscb/curation/utils.py
> +        formatted_citation = formatted_citation + formatted_contributors + '.'
`formatted_citation` is still empty at this point, isn't it? no need to prepend.

2024-01-28 21:19 UTC, jdamerow commented
yes, you can write the tests later, the other code needs to be fixed though ;)

2024-01-29 17:19 UTC, crispzips commented on isiscb/curation/utils.py
> +                break
yeah the way i was doing it was so dumb -- i think i was trying to just break the problem down step by step and I should have looked at the end result and asked how I could combine tiny steps together

2024-01-30 02:45 UTC, crispzips commented
I think i've done it all

2024-01-30 02:45 UTC, crispzips commented
I think of done all the changes

2024-01-31 01:52 UTC, jdamerow commented
There is a conflict now.

2024-01-31 02:15 UTC, jdamerow requested changes

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +                contribs.append(contrib_acrelation.authority.name)
it doesn't change the outcome, but a more pythonic way to write this would probably be
```
contribs = [acrel.authority.name for acrel in filter(lambda rel: rel.authority.name, contrib_acrelations)]
```
(I haven't tried this but I think it should work.

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +        formatted_contributors = _build_name_last_first_html(contribs[0]) + '.' # if there's just 1 contributor: "LASTNAME, Firstname"
I think you only want to add the "." if there is just one contributor, right? Right now I believe it always appends it even if it goes on afterwards.

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +        formatted_contributors = _build_name_last_first_html(contribs[0]) + '.' # if there's just 1 contributor: "LASTNAME, Firstname"
also, the comments should go on their own lines to make it more readable.

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +def _build_name_first_last_html(contrib):
add empty line before this function

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +    elif " " in contrib:
this can be just an "if" since the first if will return or go on.

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +    else:
you can remove this else (the previous if's would have returned already if they are true).

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +    else:
same as above (if ... then return, if ... then return, return default).

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +def _format_publisher_or_periodical(citation):
still true

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +    containing_citation = CCRelation.objects.filter(object_id=citation.id, type_controlled=CCRelation.INCLUDES_CHAPTER, subject__public=True).filter(public=True)
still true

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/utils.py
> +    return formatted_date
First check your boundary conditions (is date available?) and if they are not met, return right away:
```
if not date:
    return ''

if citation.type_controlled == Citation.BOOK:
    return ' ' + date.strftime('%Y') + '.'

return ('(' if formatted_publisher_or_periodical and formatted_publisher_or_periodical[-1] is ' ' else ' (') + date.strftime('%Y') + ')'
```
It doesn't change the logic but it gets rid of some indentation levels and makes it more readable.

2024-01-31 02:15 UTC, jdamerow commented on isiscb/curation/views.py
> +    context.update({'citations': queryset, 'facets': facets, 'filters': filter_params_raw, 'object_type': object_type})
break over multiple lines for readability
```
context.update({
     'citations': queryset,   
     'facets': facets, 
     'filters': filter_params_raw, 
     'object_type': object_type
})
```

2024-02-01 16:24 UTC, jdamerow requested changes

2024-02-01 16:24 UTC, jdamerow commented on isiscb/curation/utils.py
> +    containing_citation = CCRelation.objects.filter(object_id=citation.id, type_controlled=CCRelation.INCLUDES_CHAPTER, subject__public=True).filter(public=True)
still needs comments

2024-02-01 16:24 UTC, jdamerow commented on isiscb/curation/utils.py
> +    containing_citation = CCRelation.objects.filter(object_id=citation.id, type_controlled=CCRelation.INCLUDES_CHAPTER, subject__public=True).filter(public=True)
this line only seems to be used in the one if statement below, and should be defined right before the if with an empty line above, so it's visually one block.

2024-02-01 16:24 UTC, jdamerow commented on isiscb/curation/utils.py
> +    if citation.type_controlled == Citation.CHAPTER and containing_citation:
an empty line before the ifs will make it more readable

2024-02-01 16:24 UTC, jdamerow commented on isiscb/curation/utils.py
> +        if schools:
if there is no school, should it return '' or None? I believe right now it would return None, which will likely cause issues if you concatenate it with something else. Also, since the following code doesn't apply to the case where it's a thesis (it doesn't, right?), there should be another return statement in this if.

2024-02-01 16:24 UTC, jdamerow commented on isiscb/curation/utils.py
> +    if periodicals:
the contents of this if should probably go in its own method and it needs some commenting/examples.

2024-02-03 02:27 UTC, jdamerow requested changes

2024-02-03 02:27 UTC, jdamerow commented on isiscb/curation/utils.py
> +    if contribs:
if you turns this if around (`if not contribs: return ''`) you can get rid of this extra level of indentation.

2024-02-03 02:27 UTC, jdamerow commented on isiscb/curation/utils.py
> +            formatted_contributors = formatted_contributors + 'and ' + _build_name_first_last_html(contribs[1]) + '.'
isn't there a blank missing before `and`?

2024-02-03 02:27 UTC, jdamerow commented on isiscb/curation/utils.py
> +    containing_citation = CCRelation.objects.filter(object_id=citation.id, type_controlled=CCRelation.INCLUDES_CHAPTER, subject__public=True).filter(public=True)
Please add `first()`

2024-02-03 02:27 UTC, jdamerow commented on isiscb/curation/utils.py
> +    if citation.part_details:
same as in other places, turn around the if condition and return if False. Then you can remove one level of indentation and it makes it easier to read and understand.

2024-02-03 02:27 UTC, jdamerow commented on isiscb/curation/utils.py
> +            return ' ' + date.strftime('%Y') + '.'
too much indentation

2024-02-03 02:27 UTC, jdamerow commented on isiscb/curation/utils.py
> +        isbn = [linked_datum if linked_datum.type_controlled == 'ISBN' else None for linked_datum in citation.linkeddata_public][0]
if the the linked data entries are `ISSN, ISBN, URL` for instance, wouldn't this result in [None, linkedDatum, None] and therefore `isbn` would be None? I think what you want here is to filter instead?

2024-02-03 02:27 UTC, jdamerow commented on isiscb/curation/utils.py
> +        formatted_pages_or_isbn = (', ' if citation.type_controlled is 'CH' else ': ')
this should use the constant for chapter of the citation class, not be hard-coded

2024-02-03 02:27 UTC, jdamerow commented on isiscb/curation/utils.py
> +        formatted_pages_or_isbn = formatted_pages_or_isbn + '.'
what if there are no page numbers? Wouldn't that result in ", ." or ": ."?

2024-02-03 02:27 UTC, jdamerow commented on isiscb/isisdata/templates/isisdata/authority_fragments/fragment_authority_generate_html_snippet_modal.html
> +      const HTMLSnippet = document.getElementById("HTMLSnippetContent").outerHTML;
is there a reason that this variable is a const?

2024-02-03 02:27 UTC, jdamerow commented on isiscb/isisdata/templates/isisdata/authority_fragments/fragment_authority_generate_html_snippet_modal.html
> +      HTMLSnippetContainer.value = HTMLSnippet;
I know the javascript of the project is mostly a mess, but a few rules should be followed, e.g. variable names are camel case starting **with a lower case letter**. Constants should be all uppercase if they really are constants.

2024-02-03 02:27 UTC, jdamerow commented on isiscb/isisdata/templates/isisdata/authority_fragments/fragment_authority_snippet_info_box.html
> +      "Category Division": "https://isiscb-static-production.s3.amazonaws.com/isisdata/images/category_default_image.png",
are these images part of the code base? If so, the links should not be hard-coded but generated like all other static links.

2024-02-07 02:13 UTC, jdamerow commented on isiscb/curation/utils.py
> +    containing_citation = CCRelation.objects.filter(object_id=citation.id, type_controlled=CCRelation.INCLUDES_CHAPTER, subject__public=True).filter(public=True)
same here, should be declared inside the if where it's used

2024-02-07 02:18 UTC, jdamerow commented on isiscb/curation/utils.py
> +            return ' ' + date.strftime('%Y') + '.'
this still

2024-02-07 02:18 UTC, jdamerow commented on isiscb/curation/utils.py
> +        isbn = [linked_datum if linked_datum.type_controlled == 'ISBN' else None for linked_datum in citation.linkeddata_public][0]
this still

2024-02-07 02:21 UTC, jdamerow commented on isiscb/isisdata/templates/isisdata/authority_fragments/fragment_authority_snippet_info_box.html
> +      "Category Division": "https://isiscb-static-production.s3.amazonaws.com/isisdata/images/category_default_image.png",
If you use `{% static ...%}` this should be automatically be done for you and will be correct for each environment.

2024-02-07 18:27 UTC, crispzips commented
as for the {% static . . . %} generated links to images, in the DOM they appear as  `src="/static/isisdata/images/person_default_image.jpeg"` and they are copied from the DOM into wordpress so that won't work

2024-02-08 02:08 UTC, jdamerow requested changes

2024-02-08 02:08 UTC, jdamerow commented on isiscb/curation/utils.py
> +        if citation.part_details.issue_free_text:
```suggestion
        
        if citation.part_details.issue_free_text:
```

2024-02-08 02:08 UTC, jdamerow commented on isiscb/curation/utils.py
> +    return formatted_publisher_or_periodical
```suggestion
    
    return formatted_publisher_or_periodical
```

2024-02-08 02:08 UTC, jdamerow commented on isiscb/curation/utils.py
> +    isbn = None
`isbn` does not seem to be used anywhere else besides the if statement in line 144, so it should be declared there

2024-02-08 02:10 UTC, jdamerow commented
> as for the {% static . . . %} generated links to images, in the DOM they appear as `src="/static/isisdata/images/person_default_image.jpeg"` and they are copied from the DOM into wordpress so that won't work

Maybe locally, but it should happen on production since the static files are not on the same server as the app, so relative links wouldn't work and should give you a 404.

2024-02-08 02:13 UTC, crispzips commented on isiscb/curation/utils.py
> +    isbn = None
it's checked on line 148

2024-02-08 02:16 UTC, jdamerow commented on isiscb/curation/utils.py
> +    isbn = None
you mean 145? that's inside the if. Is it used anywhere outside the if?

2024-02-08 20:31 UTC, crispzips commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                        <a href="{{ citation.generate_uri }}">
@jdamerow  this is where I'm talking about

2024-02-17 02:33 UTC, jdamerow reviewed
Shouldn't all the links to authorities and citations go to the tenant page?

2024-02-17 13:55 UTC, crispzips commented
> Shouldn't all the links to authorities and citations go to the tenant page?

which links are you referring to? the links to the citations listed in `generate_newsletter_html` use the filter `get_uri` which points to the tenant portal version of the citation

2024-02-17 17:39 UTC, jdamerow commented
Yes in `generate_newsletter_html`. `get_uri` uses the tenant but only when you pass it in, which you dont' do I believe. In this for example, it only gets the citation, not the tenant:
```
<p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri }}">{{ citation.id|get_print_formatted_citation }}</a></p>
```

2024-02-19 02:32 UTC, jdamerow commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                  <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:citation.owning_tenant }}">{{ citation.id|get_print_formatted_
hm, do you want to link to the tenant that owns a citation or the tenant that the current user belongs to? If a superadmin logs in, do you want the link to go to the tenant the citation belongs to, or to the old Isiscb site (no tenant)? The way it is implemented right now would always link to the owning tenant site, which probably at the moment doesn't make a difference but if we allow in the future to see other tenants' citation or inlcude them in the newsletter feature, then this might be important? Also, right now, do you want to link from the newsletter to the new Isis portal or the old site?

2024-02-19 18:47 UTC, crispzips commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                  <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:citation.owning_tenant }}">{{ citation.id|get_print_formatted_
I thought that citations belonged to individual tenants so how could this link point to the current user's tenant or anywhere other than the tenant portal that owns the citation in question? I guess i don't understand the whole tenant situation so maybe this is a question for Dr. Weldon?

2024-02-19 19:14 UTC, jdamerow commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                  <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:citation.owning_tenant }}">{{ citation.id|get_print_formatted_
In the case of authorities, those can be shared between tenants, and in that case an authority might be owned by one tenant but used in another. In theory this can also be done for citations (you can view any citation in any tenant portal, it just might not show up in the search). Right now, I think the most pressing question is if you want newsletters generated right now to point to the old isiscb site or the portal site. @StephenPWeldon thoughts?

2024-02-19 23:25 UTC, crispzips commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                  <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:citation.owning_tenant }}">{{ citation.id|get_print_formatted_
After discussing it with Dr. Weldon, links will direct to the tenant of the user who is generating the snippet

2024-02-19 23:35 UTC, crispzips commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                  <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:citation.owning_tenant }}">{{ citation.id|get_print_formatted_
given that, how does this look: 
```
{% for citation in page_results %}
{% with request.user.tenants.all|first as tenant%}
       <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:tenant.id }}">{{ citation.id|get_print_formatted_citation }}</a></p>
{% endwith %}
{% endfor %}
```

I don't have tenants set up in my local environment so...

2024-02-20 02:38 UTC, jdamerow commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                  <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:citation.owning_tenant }}">{{ citation.id|get_print_formatted_
You should be able to just say:
```
{% for citation in page_results %}
<p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:tenant_id }}">{{ citation.id|get_print_formatted_citation }}</a></p>
{% endfor %}
```
`base.html ` in the curation template has examples of the all the context variables that are available throughout the curation interface (or also see [here](https://github.com/upconsulting/IsisCB/blob/master/isiscb/curation/context_processors.py)).

2024-02-20 02:38 UTC, jdamerow commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                  <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:citation.owning_tenant }}">{{ citation.id|get_print_formatted_
Also, go set up a tenant! ;)

2024-02-21 05:18 UTC, crispzips commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                  <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:citation.owning_tenant }}">{{ citation.id|get_print_formatted_
I did not know that about the context variables --- very helpful, so thank you

2024-02-22 03:36 UTC, jdamerow commented on isiscb/curation/templates/curation/generate_newsletter_html.html
> +                  <p class="tinos-regular" style="padding-left: 25px; text-indent: -25px; font-size: 18px;"><a href="{{ citation|get_uri:citation.owning_tenant }}">{{ citation.id|get_print_formatted_
this is not fixed yet, right? the tenant id should be changed here?

2024-02-22 03:37 UTC, jdamerow commented on isiscb/tenants/templates/tenants/citation.html
> +            <a href="{{citation | get_uri}}" style="color:#333;"><h3 style="margin: 0px">{{ citation_title|bleach_safe }} {% if pub_year %}({{ pub_year}}){% endif %}
it should link to the tenant here as well, right?

2024-02-22 03:41 UTC, jdamerow commented on isiscb/tenants/templates/tenants/authority_fragments/fragment_authority_snippet_info_box.html
> +    <a href="{% url 'haystack_search' %}?q=(subject_ids:{{ authority.id }} OR category_ids:{{ authority.id }})&models=isisdata.citation&sort_order=publication_date_for_sort&sort_order_dir=descend&raw
I'm fairly certain these search links also produce the wrong link (to the old site, not the tenant site).

2024-02-22 04:03 UTC, StephenPWeldon commented
Julia,

Can you just fix the code so that it will be operative tomorrow when I talk
with our newsletter editor?

Thanks,

Steve

On Wed, Feb 21, 2024 at 9:41 PM Julia Damerow ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> isiscb/tenants/templates/tenants/authority_fragments/fragment_authority_snippet_info_box.html
> <https://github.com/upconsulting/IsisCB/pull/805#discussion_r1498573825>:
>
> > +    {% endif %}
> +
> +    {% if publisher_count > 0 %}
> +    <i class="fa fa-bookmark" aria-hidden="true"></i>
> +    Show
> +    <a href="{% url 'haystack_search' %}?q=(publisher_ids:{{ authority.id }} OR periodical_ids:{{ authority.id }})&models=isisdata.citation&sort_order=publication_date_for_sort&sort_order_dir=descend&raw_search=True">
> +    {{publisher_count}} citations
> +    </a>
> +    related to {{ authority.name }} as a publisher
> +    <br>
> +    {% endif %}
> +
> +    {% if subject_category_count > 0 %}
> +    <i class="fa fa-bookmark" aria-hidden="true"></i>
> +    Show
> +    <a href="{% url 'haystack_search' %}?q=(subject_ids:{{ authority.id }} OR category_ids:{{ authority.id }})&models=isisdata.citation&sort_order=publication_date_for_sort&sort_order_dir=descend&raw_search=True">
>
> I'm fairly certain these search links also produce the wrong link (to the
> old site, not the tenant site).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/upconsulting/IsisCB/pull/805#pullrequestreview-1894799196>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADE5NZD6J3IF2DNKTRXZQ3LYU247FAVCNFSM6AAAAABCJPZ55WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOJUG44TSMJZGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-22 14:19 UTC, jdamerow commented
I've the links that I found and think were incorrect, but someone should probably go over all the changes and make sure I didn't miss any. I can't get this version to run on my computer right now, so I'll merge and check on staging that the changes work. Then I can push it to production.

2024-02-22 14:20 UTC, merged

2024-02-22 14:41 UTC, jdamerow commented
The links on the public authority page are still wrong. I must have missed them. (citation page is correct). I'm busy for the rest of the day, but I deploy the version as it is now to production.

2024-02-22 14:55 UTC, jdamerow commented
Also, the links on the public citation page of the old isis interface (not the tenant) are relative, not absolute. So they won't work if copied somewhere else.